<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$ourmission_title = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/ourmission/ourmission_title');
$ourmission_text1 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/ourmission/ourmission_text1');
$ourmission_text2 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/ourmission/ourmission_text2');
$ourmission_text3 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/ourmission/ourmission_text3');

echo "our mission:<br>";
echo "Title:".$ourmission_title."<br>";
echo "Text1:".$ourmission_text1."<br>";
echo "Text2:".$ourmission_text2."<br>";
echo "Text3:".$ourmission_text3."<br>";

$gopurple_title = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_title');
$gopurple_text1 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text1');
$gopurple_text2 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text2');
$gopurple_text2_1 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text2_1');
$gopurple_text3 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text3');
$gopurple_text4 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text4');
$gopurple_text5 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/gopurple/gopurple_text5');

echo "Go purple:<br>";
echo "Title:".$gopurple_title."<br>";
echo "Text1:".$gopurple_text1."<br>";
echo "Text2:".$gopurple_text2."<br>";
echo "Text2_1:".$gopurple_text2_1."<br>";
echo "Text3:".$gopurple_text3."<br>";
echo "Text4:".$gopurple_text4."<br>";
echo "Text5:".$gopurple_text5."<br>";

echo "<br>";
$earthday_text1 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/earthday/earthday_text1');
$earthday_text2 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/earthday/earthday_text2');
$earthday_text3 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('purplefortheplanet/earthday/earthday_text3');

echo "Earth Day:<br>";
echo "Text1:".$earthday_text1."<br>";
echo "Text2:".$earthday_text2."<br>";
echo "Text3:".$earthday_text3."<br>";

?>
